name: Ports
main: net.robinjam.bukkit.ports.Ports
version: ${project.version}
author: robinjam
depend: [WorldEdit]

commands:
  port:
    description: Provides access to Ports commands
    usage: /<command>

permissions:
  ports.*:
    description: Gives access to all Ports features
    default: op
    children:
      ports.reload: true
      ports.create: true
      ports.delete: true
      ports.select: true
      ports.arrive: true
      ports.update: true
      ports.schedule: true
      ports.describe: true
      ports.destination: true
      ports.link: true
      ports.unlink: true
      ports.rename: true
      ports.permission: true
      ports.ticket: true
      ports.cooldown: true
      ports.teleport: true
      
  ports.reload:
    description: Allows you to use /port reload
  
  ports.create:
    description: Allows you to use /port create
  
  ports.delete:
    description: Allows you to use /port delete
  
  ports.select:
    description: Allows you to use /port select
  
  ports.arrive:
    description: Allows you to use /port arrive
  
  ports.update:
    description: Allows you to use /port update
  
  ports.schedule:
    description: Allows you to use /port schedule
  
  ports.describe:
    description: Allows you to use /port describe
  
  ports.destination:
    description: Allows you to use /port destination
  
  ports.link:
    description: Allows you to use /port link
  
  ports.unlink:
    description: Allows you to use /port unlink
  
  ports.rename:
    description: Allows you to use /port rename

  ports.permission:
    description: Allows you to use /port permission

  ports.ticket:
    description: Allows you to use /port ticket

  ports.cooldown:
    description: Allows you to use /port cooldown

  ports.teleport:
    description: Allows you to use /port teleport
  
  ports.list:
    description: Allows you to use /port list
    default: true